### PR TITLE
feat(keyboard): Keyboard Component

### PR DESCRIPTION
**Pull request by chelseasimek**

### CODE REVIEW

**Review by chiefcll — APPROVED** [review]

**Review by mhughesacn — CHANGES_REQUESTED** [review]
Hi Chelsea,
Please insert the Comcast Apache header on all new Javascript files.  (I know that not all the existing files have headers - an audit will need to be done, but for now, let's get new stuff fixed.)  When you are done, I will approve in the tool.
Thanks,
Martin Hughes, RDK CMF Compliance Team

**Comment by chelseasimek** [comment]
@mhughesacn Apache Licenses added.

**Review by chiefcll — APPROVED** [review]

**Comment by mhughesacn** [comment]
Thanks Chelsea

**Comment by chelseasimek** [comment]
@mhughesacn can you remove your change request? I don't think I can merge until that is resolved.

**Review by mhughesacn — APPROVED** [review]

**Comment by mhughesacn** [comment]
Sorry, didn't realise I was holding it up.

**Pull request merged**
