### PR TITLE
feat: get parity with lightning-ui repo

### PR DESCRIPTION
**Pull request by BeejLuig**
- Update project file structure to match internal repo
- Update components, tests, and documentation
- All scripts should be working
- Documentation should build
- Tests should be at >90% coverage
- Licenses should be intact for all relevant files
- Project-specific references should be accurate

### CODE REVIEW

**Comment by mhughesacn** [comment]
Hi @BeejLuig 
- Please will you put CONTRIBUTING.md back in the standard place (top level dir).  If it fails to scan in Blackduck I will fix it.
Thanks,
Martin (Martin Hughes, RDK CMF Compliance Team)

**Comment by BeejLuig** [comment]
@mhughesacn `CONTRIBUTING.md` is untouched

**Comment by mhughesacn** [comment]
Sorry @BeejLuig You are right,I was looking at the first commit (where it also triggered blackduck).

**Comment by BeejLuig** [comment]
Ah, no worries @mhughesacn, thanks staying on top of it!

**Pull request merged**
