### PR TITLE
docs: extra copyright credit

### PR DESCRIPTION
**Pull request by rohantom016**
BD-1214 Extra Credit in Lightning-UI-Components

### CODE REVIEW

**Comment by erautenberg** [comment]
Thanks @rohantom016. Please run the lint fix command and you should be good to go!

**Comment by rohantom016** [comment]
> Please run the lint fix command and you should be good to go!

Hi @erautenberg ,

Could you please guide me , how to run this lint fix command?

Thanks & Regards ,
Rohan Tom

**Comment by ImCoolNowRight** [comment]
> > Please run the lint fix command and you should be good to go!
> 
> Hi @erautenberg ,
> 
> Could you please guide me , how to run this lint fix command?
> 
> Thanks & Regards , Rohan Tom

In your terminal, you can run `yarn run lint:fix`, and that should fix any formatting errors there may be!

**Comment by rohantom016** [comment]
> > > Please run the lint fix command and you should be good to go!
> > 
> > 
> > Hi @erautenberg ,
> > Could you please guide me , how to run this lint fix command?
> > Thanks & Regards , Rohan Tom
> 
> In your terminal, you can run `yarn run lint:fix`, and that should fix any formatting errors there may be!

Hi @erautenberg @ImCoolNowRight 

Successfully ran the command  `yarn run lint:fix` and pushed the changes to the repo. Please verify.

Thanks & regards,
Rohan Tom

**Comment by mhughesacn** [comment]
Hi @erautenberg & All: We are not sure what else is required to get this merged - can you help please?  Here's what has happened in other repos: A compliance problem is identified and when the fixes are non-code (or just comments), RDK has provided someone to do them, which is usually quicker than raising a ticket into the component team.  The component owner has to approve and merge.  We would not usually have the ability to do unit testing etc., and the changes we take on don't require it.
Thank you,
Martin Hughes, RDM CMF Compliance Team

**Review by ImCoolNowRight — APPROVED** [review]

**Comment by erautenberg** [comment]
@mhughesacn sorry for the delay, I missed this message. I'll merge it now, thank you again for the contribution!!

**Review by erautenberg — APPROVED** [review]

**Comment by mhughesacn** [comment]
Many thanks!

**Pull request merged**
