### PR TITLE
Create npm-publish.yml

### PR DESCRIPTION
**Pull request by BeejLuig**

### CODE REVIEW

**Comment by BeejLuig** [comment]
This file is templated by GitHub..how can we bypass the blackduck scan for this config file (and others like it)?

**Comment by mhughesacn** [comment]
Hi BeegLuig: This file is widely matching in the search tool.  It doesn't originate directly from the github docs link at the top of the file.  So (1) Where exactly did you get your copy - I would like to take a look at the site licensing and (2) I may ask you to make some small changes so that this can be justified as a boilerplate configuration file that simply has to look the same as everyone else's.  (I am thinking of extra comments.)  I appreciate that this seems like a lot of trouble for something so common but I have to be fussy.
Thanks
Martin
Martin Hughes, RDK CMF Compliance Team

**Comment by BeejLuig** [comment]
@mhughesacn This is the original workflow template: https://github.com/actions/starter-workflows/blob/08ff79c7b930315861d16bed4903ddd90bf7c05c/ci/npm-publish.yml

You can generate the file by navigating to the **Actions** tab of this repository, then clicking the **Set up this workflow** button under the **Publish Node.js Package** section.

**Comment by BeejLuig** [comment]
Also, we will inevitably need/want to make some changes to this file in order for it to work with our use case, we just don't know _what_ we need/want yet

**Comment by mhughesacn** [comment]
Thank you!  This is a solid source.  To keep compliance happy, please will you add these two lines under line 3:

"Copyright (c) 2019 GitHub
Licensed under the MIT license"

and append the same two lines to NOTICE.

Thanks,

Martin

**Comment by BeejLuig** [comment]
@mhughesacn done, lmk if there's anything else

**Comment by mhughesacn** [comment]
Thanks BeejLuig

**Review by chiefcll — APPROVED** [review]

**Pull request merged**
