### PR TITLE
build: rename ui-components-base-theme to ui-components-theme-base

### PR DESCRIPTION
**Pull request by erautenberg**
# Description

Since we'll need to add at least one or two more OS themes beyond Base in order to show the Theme Switcher working in Storybook and @Josh’s demo app, I renamed `@lightningjs/ui-components-base-theme` to `@lightningjs/ui-components-theme-base` so that in the future, all themes will be grouped together and easier to parse alphabetically (ie `@lightningjs/ui-components-theme-rainbow`).

# Test

1. `yarn install`
2. `yarn start`
3. Confirm components are still working as expected (Base theme is being applied)

### CODE REVIEW

**Review by joshhowenstine — APPROVED** [review]

**Comment by erautenberg** [comment]
Note: Scans initially failed because I accidentally pushed up some code from a different PR, this commit was fixed so those files were removed

**Review by anthony9187 — APPROVED** [review]

**Review by soumyaloka — APPROVED** [review]

**Pull request merged**
